# model/Dockerfile

# Use Python as the base image
FROM python:3.10

# Set the working directory
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose port 5001 (or your model port)
EXPOSE 5001

# Command to run the Flask app in development mode
CMD ["python", "server.py"]